export const ActionTypes = {
  //get list employee
  GET_LIST_EMPLOYEE: 'GET_LIST_EMPLOYEE',
  GET_LIST_EMPLOYEE_SUCCESS: 'GET_LIST_EMPLOYEE_SUCCESS',
  GET_LIST_EMPLOYEE_FAILED: 'GET_LIST_EMPLOYEE_FAILED',
  //add data employee
  GET_EMPLOYEE_DATA: 'GET_EMPLOYEE_DATA',
  GET_EMPLOYEE_DATA_SUCCESS: 'GET_EMPLOYEE_DATA_SUCCESS',
  ADD_EMPLOYEE_DATA: 'ADD_EMPLOYEE_DATA',
  ADD_EMPLOYEE_DATA_SUCCESS: 'ADD_EMPLOYEE_DATA_SUCCESS',
  ADD_EMPLOYEE_DATA_FAILED: 'ADD_EMPLOYEE_DATA_FAILED',
  //update data cv
  UPDATE_EMPLOYEE_DATA: 'UPDATE_EMPLOYEE_DATA',
  UPDATE_EMPLOYEE_DATA_SUCCESS: 'UPDATE_EMPLOYEE_DATA_SUCCESS',
  UPDATE_EMPLOYEE_DATA_FAILED: 'UPDATE_EMPLOYEE_DATA_FAILED',
  GET_ID_REGISTER: 'GET_ID_REGISTE',
  //update data employee
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
  UPDATE_EMPLOYEE_FAILED: 'UPDATE_EMPLOYEE_FAILED',
  //send lead
  SEND_LEAD_DATA: 'SEND_LEAD_DATA',
  SEND_LEAD_DATA_SUCCESS: 'SEND_LEAD_DATA_SUCCESS',
  SEND_LEAD_DATA_FAILED: 'SEND_LEAD_DATA_FAILED',
  //watch detail
  GET_DETAIL: 'GET_DETAIL',
  GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
  GET_DETAIL_FAILED: 'GET_DETAIL_FAILED',
  //delete employee
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
  DELETE_EMPLOYEE_FAILED: 'DELETE_EMPLOYEE_FAILED',
  //location
  GET_LIST_LOCATION: 'GET_LIST_LOCATION',
  GET_LIST_LOCATION_SUCCESS: 'GET_LIST_LOCATION_SUCCESS',
  GET_LIST_LOCATION_FAILED: 'GET_LIST_LOCATION_FAILED',
  //total employee count
  TOTAL_EMPLOYEE_COUNT: 'TOTAL_EMPLOYEE_COUNT',
  TOTAL_EMPLOYEE_COUNT_SUCCESS: 'TOTAL_EMPLOYEE_COUNT_SUCCESS',
  TOTAL_EMPLOYEE_COUNT_FAILED: 'TOTAL_EMPLOYEE_COUNT_FAILED',
  //add promte
  ADD_PROMOTE: 'ADD_PROMOTE',
  ADD_PROMOTE_SUCCESS: 'ADD_PROMOTE_SUCCESS',
  ADD_PROMOTE_FAILED: 'ADD_PROMOTE_FAILED',
  //list promte
  GET_LIST_PROMOTE: 'GET_LIST_PROMOTE',
  GET_LIST_PROMOTE_SUCCESS: 'GET_LIST_PROMOTE_SUCCESS',
  GET_LIST_PROMOTE_FAILED: 'GET_LIST_PROMOTE_FAILED',
  //delete promte
  DELETE_PROMOTE: 'DELETE_PROMOTE',
  DELETE_PROMOTE_SUCCESS: 'DELETE_PROMOTE_SUCCESS',
  DELETE_PROMOTE_FAILED: 'DELETE_PROMOTE_FAILED',
};
